"""Create initial migration

Revision ID: 46ba7490ba2e
Revises:
Create Date: 2025-08-10 14:08:30.908932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46ba7490ba2e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sitter_scores_pipelines",
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_time_update", sa.DateTime(), nullable=False),
        sa.Column("phases_completed", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "sitter_scores",
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("sitter", sa.Text(), nullable=False),
        sa.Column("profile_score", sa.Integer(), nullable=False),
        sa.Column("ratings_score", sa.Float(), nullable=True),
        sa.Column("search_score", sa.Float(), nullable=True),
        sa.Column("last_update_pipeline_FK", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_update_pipeline_FK"],
            ["sitter_scores_pipelines.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.Index("sitter_search_score", "search_score"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sitter_scores_pipelines")
    op.drop_table("sitter_scores")
    # ### end Alembic commands ###
